{
 "title": "Tefnut",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "environement", "query": "dev,stage,prod" }
  ]
 },
 "panels": [
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"tefnut-$environement\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humidity\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")"
    }
   ]
  },
  {
   "title": "Humidificator Mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"tefnut-$environement\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Status\")\n  |> filter(fn: (r) =>  r[\"_field\"] == \"state\")\n  |> last()"
    }
   ]
  },
  {
   "title": "Target Humidity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"tefnut-$environement\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humidity\")\n  |> filter(fn: (r) => r[\"_field\"] == \"target\")"
    }
   ]
  },
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"tefnut-$environement\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Status\")\n  |> filter(fn: (r) => r[\"_field\"] == \"mode\" or r[\"_field\"] == \"state\")"
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "{application=\"tefnut-$environement\",severity=\"error\"}",
     "resolution": 1
    },
    {
     "expr": "{application=\"tefnut-$environement\",severity=\"critical\"}"
    }
   ]
  },
  {
   "title": "Loop time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"tefnut-$environement\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"timming\")\n  |> filter(fn: (r) => r[\"_field\"] == \"loop time\")"
    }
   ]
  },
  {
   "title": "Tefnut version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "{application=\"tefnut-prod\", severity=\"info\"} |= `Tefnut version`"
    }
   ]
  },
  {
   "title": "Git Sha",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "{application=\"tefnut-prod\", severity=\"info\"} |= `Starting code`"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"tefnut-$environement\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humidity\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\" or r[\"_field\"] == \"target\" or r[\"_field\"] == \"state\")"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"tefnut-$environement\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current temp\" or r[\"_field\"] == \"forcast temp\" or r[\"_field\"] == \"target temp\")"
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"tefnut-$environement\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hardware\")\n  |> filter(fn: (r) => r[\"_field\"] == \"cpu\" or r[\"_field\"] == \"ram\")"
    }
   ]
  },
  {
   "title": "Polling service freshness",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"tefnut-$environement\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"timming\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temp delay\" or r[\"_field\"] == \"humidity delay\")"
    }
   ]
  },
  {
   "title": "Main loop delay",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"tefnut-$environement\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"timming\")\n  |> filter(fn: (r) => r[\"_field\"] == \"loop time\")"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "{application=\"tefnut-$environement\",severity=\"warning\"}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "{application=\"tefnut-$environement\",severity=\"error\"}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "{application=\"tefnut-$environement\",severity=\"critical\"}",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum by(severity) (count_over_time({application=\"tefnut-$environement\"}[1m]))",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Logs - Warning +",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "{application=\"tefnut-$environement\", severity=~\"critical|error|warning\"}"
    }
   ]
  },
  {
   "title": "Logs - All",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "{application=\"tefnut-$environement\"}"
    }
   ]
  }
 ]
}